blank_issues_enabled: false
contact_links: 
   - name: Disweb.py Documentation 
     url: https://invalidlenni.gitbook.io/disweb.py/
     about: Read the docs.
   - name: Libary Questions & Requests
     url; https://github.com/InvalidLenni/disweb.py/discussions
     about: The place for requesting libary ideas and questions.
   - name: API Bug Report
     url: https://github.com/diswebsite/disweb/issues/new
     about: Please report API Bugs there.
